/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRegisterBuildingRouteImport } from './routes/_authenticated/register-building'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedBuildingIdRouteImport } from './routes/_authenticated/building.$id'
import { Route as AuthenticatedBuildingIdChatRouteImport } from './routes/_authenticated/building.$id_.chat'
import { Route as AuthenticatedBuildingIdHostsRouteImport } from './routes/_authenticated/building.$id_.hosts'
import { Route as AuthenticatedBuildingIdMaintenanceRouteImport } from './routes/_authenticated/building.$id_.maintenance'
import { Route as AuthenticatedBuildingIdNotificationsRouteImport } from './routes/_authenticated/building.$id_.notifications'
import { Route as AuthenticatedBuildingIdRoomsRouteImport } from './routes/_authenticated/building.$id_.rooms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegisterBuildingRoute =
  AuthenticatedRegisterBuildingRouteImport.update({
    id: '/register-building',
    path: '/register-building',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildingIdRoute = AuthenticatedBuildingIdRouteImport.update({
  id: '/building/$id',
  path: '/building/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildingIdChatRoute =
  AuthenticatedBuildingIdChatRouteImport.update({
    id: '/building/$id_/chat',
    path: '/building/$id/chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildingIdHostsRoute =
  AuthenticatedBuildingIdHostsRouteImport.update({
    id: '/building/$id_/hosts',
    path: '/building/$id/hosts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildingIdMaintenanceRoute =
  AuthenticatedBuildingIdMaintenanceRouteImport.update({
    id: '/building/$id_/maintenance',
    path: '/building/$id/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildingIdNotificationsRoute =
  AuthenticatedBuildingIdNotificationsRouteImport.update({
    id: '/building/$id_/notifications',
    path: '/building/$id/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildingIdRoomsRoute =
  AuthenticatedBuildingIdRoomsRouteImport.update({
    id: '/building/$id_/rooms',
    path: '/building/$id/rooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/register-building': typeof AuthenticatedRegisterBuildingRoute
  '/search': typeof AuthenticatedSearchRoute
  '/building/$id': typeof AuthenticatedBuildingIdRoute
  '/building/$id/chat': typeof AuthenticatedBuildingIdChatRoute
  '/building/$id/hosts': typeof AuthenticatedBuildingIdHostsRoute
  '/building/$id/maintenance': typeof AuthenticatedBuildingIdMaintenanceRoute
  '/building/$id/notifications': typeof AuthenticatedBuildingIdNotificationsRoute
  '/building/$id/rooms': typeof AuthenticatedBuildingIdRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/register-building': typeof AuthenticatedRegisterBuildingRoute
  '/search': typeof AuthenticatedSearchRoute
  '/building/$id': typeof AuthenticatedBuildingIdRoute
  '/building/$id/chat': typeof AuthenticatedBuildingIdChatRoute
  '/building/$id/hosts': typeof AuthenticatedBuildingIdHostsRoute
  '/building/$id/maintenance': typeof AuthenticatedBuildingIdMaintenanceRoute
  '/building/$id/notifications': typeof AuthenticatedBuildingIdNotificationsRoute
  '/building/$id/rooms': typeof AuthenticatedBuildingIdRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/register-building': typeof AuthenticatedRegisterBuildingRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/building/$id': typeof AuthenticatedBuildingIdRoute
  '/_authenticated/building/$id_/chat': typeof AuthenticatedBuildingIdChatRoute
  '/_authenticated/building/$id_/hosts': typeof AuthenticatedBuildingIdHostsRoute
  '/_authenticated/building/$id_/maintenance': typeof AuthenticatedBuildingIdMaintenanceRoute
  '/_authenticated/building/$id_/notifications': typeof AuthenticatedBuildingIdNotificationsRoute
  '/_authenticated/building/$id_/rooms': typeof AuthenticatedBuildingIdRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/register-building'
    | '/search'
    | '/building/$id'
    | '/building/$id/chat'
    | '/building/$id/hosts'
    | '/building/$id/maintenance'
    | '/building/$id/notifications'
    | '/building/$id/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/register-building'
    | '/search'
    | '/building/$id'
    | '/building/$id/chat'
    | '/building/$id/hosts'
    | '/building/$id/maintenance'
    | '/building/$id/notifications'
    | '/building/$id/rooms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/register-building'
    | '/_authenticated/search'
    | '/_authenticated/building/$id'
    | '/_authenticated/building/$id_/chat'
    | '/_authenticated/building/$id_/hosts'
    | '/_authenticated/building/$id_/maintenance'
    | '/_authenticated/building/$id_/notifications'
    | '/_authenticated/building/$id_/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/register-building': {
      id: '/_authenticated/register-building'
      path: '/register-building'
      fullPath: '/register-building'
      preLoaderRoute: typeof AuthenticatedRegisterBuildingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building/$id': {
      id: '/_authenticated/building/$id'
      path: '/building/$id'
      fullPath: '/building/$id'
      preLoaderRoute: typeof AuthenticatedBuildingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building/$id_/chat': {
      id: '/_authenticated/building/$id_/chat'
      path: '/building/$id/chat'
      fullPath: '/building/$id/chat'
      preLoaderRoute: typeof AuthenticatedBuildingIdChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building/$id_/hosts': {
      id: '/_authenticated/building/$id_/hosts'
      path: '/building/$id/hosts'
      fullPath: '/building/$id/hosts'
      preLoaderRoute: typeof AuthenticatedBuildingIdHostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building/$id_/maintenance': {
      id: '/_authenticated/building/$id_/maintenance'
      path: '/building/$id/maintenance'
      fullPath: '/building/$id/maintenance'
      preLoaderRoute: typeof AuthenticatedBuildingIdMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building/$id_/notifications': {
      id: '/_authenticated/building/$id_/notifications'
      path: '/building/$id/notifications'
      fullPath: '/building/$id/notifications'
      preLoaderRoute: typeof AuthenticatedBuildingIdNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/building/$id_/rooms': {
      id: '/_authenticated/building/$id_/rooms'
      path: '/building/$id/rooms'
      fullPath: '/building/$id/rooms'
      preLoaderRoute: typeof AuthenticatedBuildingIdRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRegisterBuildingRoute: typeof AuthenticatedRegisterBuildingRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedBuildingIdRoute: typeof AuthenticatedBuildingIdRoute
  AuthenticatedBuildingIdChatRoute: typeof AuthenticatedBuildingIdChatRoute
  AuthenticatedBuildingIdHostsRoute: typeof AuthenticatedBuildingIdHostsRoute
  AuthenticatedBuildingIdMaintenanceRoute: typeof AuthenticatedBuildingIdMaintenanceRoute
  AuthenticatedBuildingIdNotificationsRoute: typeof AuthenticatedBuildingIdNotificationsRoute
  AuthenticatedBuildingIdRoomsRoute: typeof AuthenticatedBuildingIdRoomsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRegisterBuildingRoute: AuthenticatedRegisterBuildingRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedBuildingIdRoute: AuthenticatedBuildingIdRoute,
  AuthenticatedBuildingIdChatRoute: AuthenticatedBuildingIdChatRoute,
  AuthenticatedBuildingIdHostsRoute: AuthenticatedBuildingIdHostsRoute,
  AuthenticatedBuildingIdMaintenanceRoute:
    AuthenticatedBuildingIdMaintenanceRoute,
  AuthenticatedBuildingIdNotificationsRoute:
    AuthenticatedBuildingIdNotificationsRoute,
  AuthenticatedBuildingIdRoomsRoute: AuthenticatedBuildingIdRoomsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
